[package]
name = "nmed"
version = "0.1.0"
edition = "2021"
description = "No Modifier EDitor: A simple text editor that requires no modifier keys like Ctrl or Alt."

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
color-eyre = "0.6.3"
fancy-regex = "0.13.0"
ratatui = "0.28.1"
